name: Run Laravel Tests

on:
  workflow_call:
    inputs:
      database:
        required: true
        type: string
      php_version:
        required: false
        type: string
        default: "8.0"
      postgres_user:
        required: false
        type: string
        default: "postgres"
      postgres_password:
        required: false
        type: string
        default: "password"

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:${{ inputs.php_version }}

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: ${{ postgres_user }}
          POSTGRES_PASSWORD: ${{ postgres_password }}
          POSTGRES_DB: ${{ inputs.database }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.testing .env

      - name: Run Tests
        run: vendor/bin/phpunit tests/
